version: "3"

services:
  app:
    image: jboss/keycloak:15.0.0
    container_name: micro-auth-app
    volumes:
      - ./.docker/keycloak/data:/opt/jboss/keycloak/standalone/data
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - 9090:8080